# Generated by Django 4.2.5 on 2023-11-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dndapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("race", models.CharField(max_length=50)),
                ("classes", models.CharField(max_length=200)),
                ("alignment", models.CharField(max_length=50)),
                ("backstory", models.TextField()),
                ("lifestyle", models.CharField(max_length=100)),
                ("level", models.IntegerField()),
                ("gold", models.DecimalField(decimal_places=2, max_digits=10)),
                ("downtime", models.IntegerField()),
                ("factions", models.CharField(max_length=200)),
                ("player_comment", models.TextField(blank=True)),
                ("external_link", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
