# Generated by Django 4.2.5 on 2023-11-14 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dndapp", "0010_complaint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint", old_name="description", new_name="details",
        ),
        migrations.RenameField(
            model_name="complaint", old_name="created_at", new_name="submitted_on",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="against_game_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dndapp.gamesession",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="against_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
